name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Run tests
        run: pnpm test

      - name: Start project
        run: pnpm start
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          PORT: ${{ secrets.PORT }}
          PRISMA_DISABLE_WARNINGS: "1"
