name: Run Tests on Push to develop

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install && pnpm add -D ts-node typescript @types/node
      - name: Run tests
        run: pnpm test
      - name: Upload test results
        if: ${{ failure() }}
        run: echo "Тесты завершились с ошибкой. Проверьте логи выше."
      - name: Success message
        if: ${{ success() }}
        run: echo "Все этапы CI/CD прошли успешно!"
